// Generated from TypeScript by npm run build. Do not edit this file directly.
'use strict';
const __modules = {
"src/config.js": function(module, exports, require, __filename, __dirname) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.riskName = exports.slotCount = exports.isWtf = exports.WTF_RISK = exports.PASS2_NONCES_PUBLISHED = exports.CONVERGENCE_STEP = exports.PLINKO_CONFIG_SHA256 = void 0;
exports.configSha256 = configSha256;
exports.loadPlinkoConfig = loadPlinkoConfig;
exports.payoutTable = payoutTable;
exports.payoutMultiplier = payoutMultiplier;
exports.binomP = binomP;
exports.theoreticalRTP = theoreticalRTP;
exports.allConfigs = allConfigs;
const node_fs_1 = require("node:fs");
const node_crypto_1 = require("node:crypto");
const node_path_1 = require("node:path");
const CONFIG_PATH = (0, node_path_1.join)(__dirname, '..', 'plinkoConfig.json');
exports.PLINKO_CONFIG_SHA256 = 'f8eaf67e1ffc63ee0dc21123447581c55f443c167dcb451b45ab7cd108fe712f';
function configSha256() {
    return (0, node_crypto_1.createHash)('sha256').update((0, node_fs_1.readFileSync)(CONFIG_PATH)).digest('hex');
}
function loadPlinkoConfig(expected = exports.PLINKO_CONFIG_SHA256) {
    if (!(0, node_fs_1.existsSync)(CONFIG_PATH)) {
        console.error(`ERROR: plinko config not found at ${CONFIG_PATH}`);
        process.exit(1);
    }
    const raw = (0, node_fs_1.readFileSync)(CONFIG_PATH);
    const sha256 = (0, node_crypto_1.createHash)('sha256').update(raw).digest('hex');
    if (expected && sha256 !== expected) {
        console.error('ERROR: plinkoConfig.json SHA-256 mismatch — table differs from the audited artifact');
        console.error(`  expected: ${expected}`);
        console.error(`  actual:   ${sha256}`);
        process.exit(1);
    }
    return JSON.parse(raw.toString('utf8'));
}
exports.CONVERGENCE_STEP = 50000;
exports.PASS2_NONCES_PUBLISHED = 10000;
exports.WTF_RISK = 4;
const isWtf = (riskLevel) => riskLevel === exports.WTF_RISK;
exports.isWtf = isWtf;
const slotCount = (rows) => rows + 1;
exports.slotCount = slotCount;
function payoutTable(cfg, rows, riskLevel) {
    if ((0, exports.isWtf)(riskLevel)) {
        if (rows !== cfg.wtf_mode.rows)
            throw new Error(`WTF rows must be ${cfg.wtf_mode.rows}, got ${rows}`);
        return cfg.wtf_mode.odds;
    }
    const bucket = cfg.payout_tables[String(rows)];
    if (!bucket)
        throw new Error(`rows=${rows} not in config`);
    const arr = bucket[riskLevel - 1];
    if (!arr)
        throw new Error(`riskLevel=${riskLevel} not in config for rows=${rows}`);
    return arr;
}
function payoutMultiplier(cfg, rows, riskLevel, slot) {
    return payoutTable(cfg, rows, riskLevel)[slot];
}
function binomP(rows, k) {
    let c = 1;
    for (let i = 0; i < k; i++)
        c = (c * (rows - i)) / (i + 1);
    return c * Math.pow(0.5, rows);
}
function theoreticalRTP(cfg, rows, riskLevel) {
    const t = payoutTable(cfg, rows, riskLevel);
    let rtp = 0;
    for (let k = 0; k <= rows; k++)
        rtp += binomP(rows, k) * t[k];
    return rtp;
}
function allConfigs(cfg, includeWtf = true) {
    const out = [];
    for (let rows = cfg.rows.min; rows <= cfg.rows.max; rows++)
        for (const r of [1, 2, 3])
            out.push({ rows, riskLevel: r });
    if (includeWtf)
        out.push({ rows: cfg.wtf_mode.rows, riskLevel: cfg.wtf_mode.riskLevel });
    return out;
}
const riskName = (cfg, riskLevel) => cfg.riskLevels[String(riskLevel)] ?? `risk${riskLevel}`;
exports.riskName = riskName;

},
"src/replay.js": function(module, exports, require, __filename, __dirname) {
"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
const fs = __importStar(require("fs"));
const path = __importStar(require("path"));
const rng_1 = require("./rng");
const stats_1 = require("./stats");
const config_1 = require("./config");
const cfg = (0, config_1.loadPlinkoConfig)();
const OUTPUTS_DIR = path.join(__dirname, '..', 'outputs');
const SIM_PATH = path.join(OUTPUTS_DIR, 'simulation-results.json');
const RTOL = 1e-12;
const ATOL = 1e-14;
function agree(a, b) {
    if (a === b)
        return true;
    if (!Number.isFinite(a) || !Number.isFinite(b))
        return false;
    return Math.abs(a - b) <= ATOL + RTOL * Math.max(Math.abs(a), Math.abs(b));
}
function simulateSlot(serverSeed, clientSeed, nonce, rows) {
    let slot = 0;
    for (let i = 0; i < rows; i++)
        slot += (0, rng_1.generateProvablyFairNumber)(serverSeed, clientSeed, nonce, i + 1, 2);
    return slot;
}
function binomialExpected(rows, n) {
    const p = Math.pow(0.5, rows);
    return Array.from({ length: rows + 1 }, (_, k) => (0, stats_1.combination)(rows, k) * p * n);
}
console.log('═'.repeat(60));
console.log('  LIQD PLINKO — PASS 1 HISTORICAL REPLAY');
console.log('  Re-executes the COMMITTED experiment from its saved seeds.');
console.log('  Reads outputs/simulation-results.json. Writes nothing.');
console.log('═'.repeat(60) + '\n');
if (!fs.existsSync(SIM_PATH)) {
    console.error('  [ERROR] outputs/simulation-results.json not found — nothing to replay.');
    process.exit(1);
}
const sim = JSON.parse(fs.readFileSync(SIM_PATH, 'utf-8'));
const pass1 = sim.pass1_fresh_seeds ?? {};
const rows = pass1.results ?? [];
const roundsPerConfig = pass1.roundsPerConfig ?? 0;
const expected = (0, config_1.allConfigs)(cfg);
const key = (r, k) => `${r}r/${k}`;
const wantKeys = expected.map(c => key(c.rows, c.riskLevel));
const gotKeys = rows.map(r => key(r.rows, r.riskLevel));
const missing = wantKeys.filter(k => !gotKeys.includes(k));
const strangers = [...new Set(gotKeys.filter(k => !wantKeys.includes(k)))];
const duplicates = [...new Set(gotKeys.filter((k, i) => gotKeys.indexOf(k) !== i))];
const problems = [];
if (!(roundsPerConfig > 0))
    problems.push(`roundsPerConfig is ${roundsPerConfig}`);
if (missing.length)
    problems.push(`${missing.length} configuration(s) absent from the artifact: ${missing.slice(0, 6).join(', ')}`);
if (strangers.length)
    problems.push(`${strangers.length} row(s) on a board the config does not declare: ${strangers.join(', ')}`);
if (duplicates.length)
    problems.push(`${duplicates.length} board(s) present more than once: ${duplicates.join(', ')}`);
if (problems.length) {
    console.error('  [ERROR] the committed Pass 1 artifact is not a replayable experiment:');
    for (const p of problems)
        console.error(`          ${p}`);
    process.exit(1);
}
const limitEnv = process.env.REPLAY_CONFIGS;
const limit = limitEnv !== undefined ? parseInt(limitEnv, 10) : rows.length;
const partial = !(Number.isFinite(limit) && limit >= rows.length);
const toReplay = partial ? rows.slice(0, Math.max(0, limit)) : rows;
console.log(`  ${toReplay.length}/${rows.length} configurations × ${roundsPerConfig.toLocaleString()} rounds`
    + (partial ? '  [PARTIAL — REPLAY_CONFIGS is set; this is not a publication replay]' : '') + '\n');
const failures = [];
let fieldsCompared = 0;
let convergencePoints = 0;
let maxRelDiff = 0;
const started = Date.now();
for (let i = 0; i < toReplay.length; i++) {
    const row = toReplay[i];
    const label = key(row.rows, row.riskLevel);
    if (typeof row.serverSeed !== 'string' || typeof row.clientSeed !== 'string'
        || !/^[0-9a-f]{32}$/.test(row.serverSeed) || row.clientSeed.length === 0) {
        failures.push(`${label}: the row carries no usable saved seeds, so it cannot be replayed`);
        continue;
    }
    const table = (0, config_1.payoutTable)(cfg, row.rows, row.riskLevel);
    const slotFreq = new Array(row.rows + 1).fill(0);
    const winSequence = new Uint8Array(roundsPerConfig);
    let payoutSum = 0;
    const convergence = [];
    for (let nonce = 0; nonce < roundsPerConfig; nonce++) {
        const slot = simulateSlot(row.serverSeed, row.clientSeed, nonce, row.rows);
        slotFreq[slot]++;
        payoutSum += table[slot];
        winSequence[nonce] = slot > row.rows / 2 ? 0 : 1;
        if ((nonce + 1) % config_1.CONVERGENCE_STEP === 0)
            convergence.push(payoutSum / (nonce + 1));
    }
    const { chi2, df, pValue } = (0, stats_1.chiSquaredTest)([...slotFreq], binomialExpected(row.rows, roundsPerConfig));
    const seq = Array.from(winSequence);
    const r1 = (0, stats_1.lag1Autocorrelation)(seq);
    const r1Z = r1 * Math.sqrt(roundsPerConfig);
    const { z: runsZ, pValue: runsP } = (0, stats_1.runsTest)(seq);
    const simRTP = payoutSum / roundsPerConfig;
    const theory = (0, config_1.theoreticalRTP)(cfg, row.rows, row.riskLevel);
    const cmp = (name, rec, stored) => {
        fieldsCompared++;
        if (typeof stored !== 'number' || !Number.isFinite(stored) || !agree(rec, stored)) {
            failures.push(`${label} ${name}: replayed ${rec} vs committed ${String(stored)}`);
            return;
        }
        const rel = rec === stored ? 0 : Math.abs(rec - stored) / Math.max(1e-300, Math.abs(rec), Math.abs(stored));
        if (rel > maxRelDiff)
            maxRelDiff = rel;
    };
    cmp('slotChi2', chi2, row.slotChi2);
    cmp('slotDf', df, row.slotDf);
    cmp('slotPValue', pValue, row.slotPValue);
    cmp('r1', r1, row.r1);
    cmp('r1Z', r1Z, row.r1Z);
    cmp('runsZ', runsZ, row.runsZ);
    cmp('runsPValue', runsP, row.runsPValue);
    cmp('simRTP', simRTP, row.simRTP);
    cmp('theoreticalRTP', theory, row.theoreticalRTP);
    const storedConv = Array.isArray(row.convergence) ? row.convergence : [];
    if (storedConv.length !== convergence.length) {
        failures.push(`${label} convergence: replayed ${convergence.length} point(s) vs committed ${storedConv.length}`);
    }
    else {
        for (let j = 0; j < convergence.length; j++) {
            convergencePoints++;
            cmp(`convergence[${j}]`, convergence[j], storedConv[j]);
        }
    }
    process.stdout.write(`\r  replayed ${i + 1}/${toReplay.length} — ${label.padEnd(8)} `
        + `${failures.length === 0 ? 'no differences so far' : `${failures.length} difference(s)`}   `);
}
process.stdout.write('\n\n');
const elapsed = ((Date.now() - started) / 1000).toFixed(1);
console.log('═'.repeat(60));
console.log(`  Configurations replayed: ${toReplay.length}/${rows.length}`);
console.log(`  Numeric fields compared: ${fieldsCompared} (of which ${convergencePoints} convergence points)`);
console.log(`  Max relative difference: ${maxRelDiff.toExponential(3)} (tolerance ${RTOL.toExponential(0)} relative, ${ATOL.toExponential(0)} absolute)`);
console.log(`  Time: ${elapsed}s`);
if (failures.length > 0) {
    console.log(`\n  REPLAY FAILED — ${failures.length} difference(s):`);
    for (const f of failures.slice(0, 20))
        console.log(`    ${f}`);
    if (failures.length > 20)
        console.log(`    +${failures.length - 20} more`);
    console.log('═'.repeat(60) + '\n');
    process.exit(1);
}
if (partial) {
    console.log('\n  PARTIAL REPLAY — REPLAY_CONFIGS was set, so this is not a reproduction of the');
    console.log('  published experiment. Re-run without REPLAY_CONFIGS.');
    console.log('═'.repeat(60) + '\n');
    process.exit(1);
}
console.log('\n  REPLAY OK — the committed Pass 1 experiment reproduces from its saved seeds.');
console.log('  This is numerical reproducibility. It does not establish who ran the original');
console.log('  experiment or when; that is provenance, and no offline artifact settles it.');
console.log('═'.repeat(60) + '\n');

},
"src/rng.js": function(module, exports, require, __filename, __dirname) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.commitHash = commitHash;
exports.sha256Buffer = sha256Buffer;
exports.getProvablyFairHmacSalt = getProvablyFairHmacSalt;
exports.generateProvablyFairNumber = generateProvablyFairNumber;
exports.revealPlinko = revealPlinko;
const node_crypto_1 = require("node:crypto");
function commitHash(serverSeedHexString) {
    return (0, node_crypto_1.createHash)('sha256').update(serverSeedHexString, 'utf8').digest('hex');
}
function sha256Buffer(buf) {
    return (0, node_crypto_1.createHash)('sha256').update(buf).digest('hex');
}
function getProvablyFairHmacSalt(clientSeed, nonce, cursor) {
    return `${clientSeed}:${nonce}:${cursor}`;
}
function generateProvablyFairNumber(serverSeed, clientSeed, nonce, cursor, range) {
    const key = Buffer.from(serverSeed, 'hex');
    const digest = (0, node_crypto_1.createHmac)('sha256', key)
        .update(getProvablyFairHmacSalt(clientSeed, nonce, cursor))
        .digest();
    const maxFair = Math.floor(4294967296 / range) * range;
    for (let offset = 0; offset + 4 <= digest.length; offset += 4) {
        const chunk = digest.readUInt32BE(offset);
        if (chunk < maxFair)
            return chunk % range;
    }
    return generateProvablyFairNumber(serverSeed, clientSeed, nonce, cursor + 1000000, range);
}
function revealPlinko(serverSeed, clientSeed, nonce, numberOfRows) {
    let path = '';
    for (let i = 0; i < numberOfRows; i++) {
        const bit = generateProvablyFairNumber(serverSeed, clientSeed, nonce, i + 1, 2);
        path += `${bit}`;
    }
    const winningSlot = path.split('').filter((c) => c === '1').length;
    return { path, winningSlot };
}

},
"src/stats.js": function(module, exports, require, __filename, __dirname) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.combination = combination;
exports.regularizedGamma = regularizedGamma;
exports.logGamma = logGamma;
exports.chiSquaredPValue = chiSquaredPValue;
exports.chiSquaredTest = chiSquaredTest;
exports.lag1Autocorrelation = lag1Autocorrelation;
exports.runsTest = runsTest;
exports.inverseCriticalZ = inverseCriticalZ;
exports.normalCDF = normalCDF;
exports.binomialSurvival = binomialSurvival;
function combination(n, k) {
    if (k < 0 || k > n)
        return 0;
    if (k === 0 || k === n)
        return 1;
    k = Math.min(k, n - k);
    let c = 1;
    for (let i = 0; i < k; i++) {
        c = (c * (n - i)) / (i + 1);
    }
    return c;
}
function regularizedGamma(a, x) {
    if (x < 0 || a <= 0)
        return NaN;
    if (x === 0)
        return 0;
    const gln = logGamma(a);
    if (x < a + 1) {
        let ap = a;
        let sum = 1 / a;
        let del = sum;
        for (let n = 0; n < 200; n++) {
            ap += 1;
            del *= x / ap;
            sum += del;
            if (Math.abs(del) < Math.abs(sum) * 1e-14)
                break;
        }
        return sum * Math.exp(-x + a * Math.log(x) - gln);
    }
    else {
        let b = x + 1 - a;
        let c = 1 / 1e-300;
        let d = 1 / b;
        let h = d;
        for (let i = 1; i <= 200; i++) {
            const an = -i * (i - a);
            b += 2;
            d = an * d + b;
            if (Math.abs(d) < 1e-300)
                d = 1e-300;
            c = b + an / c;
            if (Math.abs(c) < 1e-300)
                c = 1e-300;
            d = 1 / d;
            const delta = d * c;
            h *= delta;
            if (Math.abs(delta - 1) < 1e-14)
                break;
        }
        return 1 - Math.exp(-x + a * Math.log(x) - gln) * h;
    }
}
function logGamma(x) {
    const c = [
        76.18009172947146, -86.50532032941677, 24.01409824083091,
        -1.231739572450155, 0.1208650973866179e-2, -0.5395239384953e-5,
    ];
    let y = x;
    let tmp = x + 5.5;
    tmp -= (x + 0.5) * Math.log(tmp);
    let ser = 1.000000000190015;
    for (let j = 0; j < 6; j++)
        ser += c[j] / ++y;
    return -tmp + Math.log((2.5066282746310005 * ser) / x);
}
function chiSquaredPValue(chiSq, df) {
    return 1 - regularizedGamma(df / 2, chiSq / 2);
}
function chiSquaredTest(observed, expected) {
    if (observed.length !== expected.length)
        throw new Error('length mismatch');
    const obs = [...observed];
    const exp = [...expected];
    while (obs.length > 2 && exp[0] < 5) {
        obs[1] += obs[0];
        exp[1] += exp[0];
        obs.shift();
        exp.shift();
    }
    while (obs.length > 2 && exp[exp.length - 1] < 5) {
        const n = obs.length;
        obs[n - 2] += obs[n - 1];
        exp[n - 2] += exp[n - 1];
        obs.pop();
        exp.pop();
    }
    let chi2 = 0;
    for (let i = 0; i < obs.length; i++) {
        if (exp[i] > 0)
            chi2 += (obs[i] - exp[i]) ** 2 / exp[i];
    }
    const df = obs.length - 1;
    return { chi2, df, pValue: chiSquaredPValue(chi2, df) };
}
function lag1Autocorrelation(series) {
    const n = series.length;
    let mean = 0;
    for (let i = 0; i < n; i++)
        mean += series[i];
    mean /= n;
    let num = 0, den = 0;
    for (let i = 0; i < n - 1; i++)
        num += (series[i] - mean) * (series[i + 1] - mean);
    for (let i = 0; i < n; i++)
        den += (series[i] - mean) ** 2;
    return den === 0 ? 0 : num / den;
}
function runsTest(series) {
    const n = series.length;
    let n1 = 0, runs = 1;
    let prev = series[0];
    if (prev === 1)
        n1++;
    for (let i = 1; i < n; i++) {
        if (series[i] === 1)
            n1++;
        if (series[i] !== prev) {
            runs++;
            prev = series[i];
        }
    }
    const n2 = n - n1;
    const expected = (2 * n1 * n2) / n + 1;
    const varRuns = (2 * n1 * n2 * (2 * n1 * n2 - n)) / (n * n * (n - 1));
    const z = varRuns > 0 ? (runs - expected) / Math.sqrt(varRuns) : 0;
    const pValue = 2 * (1 - normalCDF(Math.abs(z)));
    return { runs, expected, z, pValue };
}
function inverseCriticalZ(alpha) {
    const p = alpha / 2;
    const t = Math.sqrt(-2 * Math.log(p));
    const c0 = 2.515517, c1 = 0.802853, c2 = 0.010328;
    const d1 = 1.432788, d2 = 0.189269, d3 = 0.001308;
    return t - (c0 + c1 * t + c2 * t * t) / (1 + d1 * t + d2 * t * t + d3 * t * t * t);
}
function normalCDF(z) {
    return 0.5 * (1 + erf(z / Math.SQRT2));
}
function binomialSurvival(k, n, p) {
    let cum = 0;
    for (let i = 0; i < k; i++)
        cum += combination(n, i) * Math.pow(p, i) * Math.pow(1 - p, n - i);
    return 1 - cum;
}
function erf(x) {
    const t = 1 / (1 + 0.3275911 * Math.abs(x));
    const y = 1 - (((((1.061405429 * t - 1.453152027) * t) + 1.421413741) * t
        - 0.284496736) * t + 0.254829592) * t * Math.exp(-x * x);
    return Math.sign(x) * y;
}

},
"src/types.js": function(module, exports, require, __filename, __dirname) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });

}
};
// Bundled modules receive their original directory paths for evidence-file lookup.
const __path = require('node:path');
const __createRequire = require('node:module').createRequire;
const __cache = new Map();
function __load(id) {
  if (__cache.has(id)) return __cache.get(id).exports;
  if (!Object.hasOwn(__modules, id)) throw new Error(`Missing bundled module: ${id}`);
  const filename = __path.join(__dirname, id);
  const diskRequire = __createRequire(filename);
  const module = { exports: {} };
  __cache.set(id, module);
  const localRequire = spec => {
    if (!spec.startsWith('.')) return diskRequire(spec);
    const joined = __path.posix.normalize(__path.posix.join(__path.posix.dirname(id), spec));
    const target = [joined, joined + '.js', joined + '/index.js']
      .find(candidate => Object.hasOwn(__modules, candidate));
    return target ? __load(target) : diskRequire(spec);
  };
  __modules[id](module, module.exports, localRequire, filename, __path.dirname(filename));
  return module.exports;
}

// The unit sources use Mocha's describe/it interface and synchronous timeout settings.
// Node's built-in runner supplies assertion reporting and a nonzero failure exit status.
function __installTestGlobals() {
  const test = require('node:test');
  const context = () => ({ timeout() {}, slow() {}, retries() {} });
  const wrap = fn => typeof fn === 'function' ? function () { return fn.call(context()); } : fn;
  for (const name of ['describe', 'it']) {
    const bind = fn => (title, callback) => fn(title, wrap(callback));
    const bound = bind(test[name]);
    for (const modifier of ['skip', 'only', 'todo']) bound[modifier] = bind(test[name][modifier]);
    globalThis[name] = bound;
  }
  for (const name of ['before', 'after', 'beforeEach', 'afterEach']) {
    globalThis[name] = callback => test[name](wrap(callback));
  }
}

__load("src/replay.js");
