// Generated from TypeScript by npm run build. Do not edit this file directly.
'use strict';
const __modules = {
"src/calibration.js": function(module, exports, require, __filename, __dirname) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CALIBRATION_METHOD = exports.Z_LEFT_TAIL = void 0;
exports.payoutMuSd = payoutMuSd;
exports.payoutValueDistribution = payoutValueDistribution;
exports.leftTailSumThreshold = leftTailSumThreshold;
exports.exactLeftTailProbability = exactLeftTailProbability;
exports.enumerationLeftTailProbability = enumerationLeftTailProbability;
exports.poissonBinomialPmf = poissonBinomialPmf;
exports.poissonBinomialSurvival = poissonBinomialSurvival;
exports.boardOfEpoch = boardOfEpoch;
exports.betsByHash = betsByHash;
exports.revealedEpochConfigs = revealedEpochConfigs;
exports.calibrateLeftTailCount = calibrateLeftTailCount;
exports.calibratedSurvival = calibratedSurvival;
const config_1 = require("./config");
exports.Z_LEFT_TAIL = 1.645;
const LATTICE_SCALE = 10;
function payoutMuSd(cfg, rows, riskLevel) {
    const t = (0, config_1.payoutTable)(cfg, rows, riskLevel);
    const mu = (0, config_1.theoreticalRTP)(cfg, rows, riskLevel);
    let ex2 = 0;
    for (let k = 0; k <= rows; k++)
        ex2 += (0, config_1.binomP)(rows, k) * t[k] * t[k];
    return { mu, sd: Math.sqrt(ex2 - mu * mu) };
}
function payoutValueDistribution(cfg, rows, riskLevel) {
    const t = (0, config_1.payoutTable)(cfg, rows, riskLevel);
    const merged = new Map();
    for (let k = 0; k <= rows; k++)
        merged.set(t[k], (merged.get(t[k]) ?? 0) + (0, config_1.binomP)(rows, k));
    return [...merged.entries()]
        .map(([value, prob]) => ({ value, prob }))
        .sort((a, b) => a.value - b.value);
}
function leftTailSumThreshold(mu, sd, n, z) {
    return n * mu - z * sd * Math.sqrt(n);
}
function gcd(a, b) {
    a = Math.abs(a);
    b = Math.abs(b);
    while (b > 0) {
        const t = a % b;
        a = b;
        b = t;
    }
    return a;
}
function exactLeftTailProbability(dist, n, threshold) {
    if (!Number.isInteger(n) || n <= 0)
        throw new Error(`exactLeftTailProbability: n must be a positive integer, got ${n}`);
    if (!Number.isFinite(threshold))
        throw new Error('exactLeftTailProbability: threshold must be finite');
    if (dist.length === 0)
        throw new Error('exactLeftTailProbability: empty distribution');
    const scaled = dist.map(({ value }) => {
        const s = Math.round(value * LATTICE_SCALE);
        if (Math.abs(value * LATTICE_SCALE - s) > 1e-9) {
            throw new Error(`exactLeftTailProbability: payout ${value} is not a multiple of ${1 / LATTICE_SCALE}`);
        }
        if (s < 0)
            throw new Error(`exactLeftTailProbability: negative payout ${value}`);
        return s;
    });
    let unit = 0;
    for (const s of scaled)
        unit = gcd(unit, s);
    if (unit === 0)
        unit = 1;
    const wAbs = scaled.map(s => s / unit);
    const wMin = Math.min(...wAbs);
    const w = wAbs.map(x => x - wMin);
    const p = dist.map(d => d.prob);
    const wMax = Math.max(...w);
    const tLattice = (threshold * LATTICE_SCALE) / unit;
    const isLatticePoint = Math.abs(tLattice - Math.round(tLattice)) < 1e-9;
    const capAbs = isLatticePoint ? Math.round(tLattice) - 1 : Math.floor(tLattice);
    const cap = capAbs - n * wMin;
    const latticeUnit = unit / LATTICE_SCALE;
    if (cap < 0)
        return { probability: 0, latticeUnit, states: 0 };
    if (wMax === 0)
        return { probability: 1, latticeUnit, states: 1 };
    let cur = new Float64Array(cap + 1);
    let next = new Float64Array(cap + 1);
    cur[0] = 1;
    let hi = 0;
    for (let j = 0; j < n; j++) {
        const newHi = Math.min(cap, hi + wMax);
        next.fill(0, 0, newHi + 1);
        for (let i = 0; i < w.length; i++) {
            const wi = w[i];
            const pi = p[i];
            if (pi === 0)
                continue;
            const end = Math.min(hi, cap - wi);
            for (let s = 0; s <= end; s++) {
                const c = cur[s];
                if (c !== 0)
                    next[s + wi] += c * pi;
            }
        }
        hi = newHi;
        const swap = cur;
        cur = next;
        next = swap;
    }
    let acc = 0;
    for (let s = 0; s <= hi; s++)
        acc += cur[s];
    return { probability: acc, latticeUnit, states: cap + 1 };
}
function enumerationLeftTailProbability(dist, n, threshold) {
    if (dist.length > 3)
        return null;
    const sorted = [...dist].sort((a, b) => a.value - b.value);
    const base = sorted[0];
    const rest = sorted.slice(1);
    const logFact = [0];
    for (let i = 1; i <= n; i++)
        logFact.push(logFact[i - 1] + Math.log(i));
    const logP = sorted.map(d => (d.prob > 0 ? Math.log(d.prob) : -Infinity));
    let acc = 0;
    const v1 = rest[0]?.value ?? 0;
    const v2 = rest[1]?.value ?? 0;
    const maxC2 = rest.length > 1 && v2 > 0 ? Math.floor(Math.max(0, threshold - n * base.value) / v2) : 0;
    for (let c2 = 0; c2 <= maxC2; c2++) {
        const maxC1 = rest.length > 0 && v1 > 0
            ? Math.floor(Math.max(0, threshold - n * base.value - c2 * v2) / v1)
            : 0;
        for (let c1 = 0; c1 <= maxC1; c1++) {
            const c0 = n - c1 - c2;
            if (c0 < 0)
                break;
            if (!(n * base.value + c1 * v1 + c2 * v2 < threshold))
                continue;
            const lp = logFact[n] - logFact[c0] - logFact[c1] - logFact[c2]
                + c0 * logP[0] + c1 * logP[1] + (rest.length > 1 ? c2 * logP[2] : 0);
            if (Number.isFinite(lp))
                acc += Math.exp(lp);
        }
    }
    return acc;
}
function poissonBinomialPmf(ps) {
    let pmf = new Float64Array(1);
    pmf[0] = 1;
    for (const p of ps) {
        const next = new Float64Array(pmf.length + 1);
        for (let k = 0; k < pmf.length; k++) {
            next[k] += pmf[k] * (1 - p);
            next[k + 1] += pmf[k] * p;
        }
        pmf = next;
    }
    return pmf;
}
function poissonBinomialSurvival(ps, k) {
    const pmf = poissonBinomialPmf(ps);
    let acc = 0;
    for (let i = Math.max(0, k); i < pmf.length; i++)
        acc += pmf[i];
    return Math.min(1, Math.max(0, acc));
}
function boardOfEpoch(epochBets) {
    let best = null;
    for (const b of epochBets) {
        if (best === null
            || b.nonce < best.nonce
            || (b.nonce === best.nonce && (b.numberOfRows < best.numberOfRows
                || (b.numberOfRows === best.numberOfRows && b.riskLevel < best.riskLevel)))) {
            best = b;
        }
    }
    return best === null ? null : { rows: best.numberOfRows, riskLevel: best.riskLevel };
}
function betsByHash(bets) {
    const m = new Map();
    for (const b of bets) {
        const arr = m.get(b.hashedServerSeed) ?? [];
        arr.push(b);
        m.set(b.hashedServerSeed, arr);
    }
    return m;
}
function revealedEpochConfigs(bets, seeds) {
    const byHash = betsByHash(bets);
    return seeds
        .filter(s => !!s.serverSeed)
        .map(s => {
        const board = boardOfEpoch(byHash.get(s.hashedServerSeed) ?? []);
        return {
            epoch: s.epoch,
            rows: board?.rows ?? 16,
            riskLevel: board?.riskLevel ?? 3,
        };
    });
}
exports.CALIBRATION_METHOD = 'exact lattice convolution of the per-drop payout distribution (independent binomial x pinned payout table) '
    + 'over the window, truncated at the threshold; aggregated across epochs as an exact Poisson-binomial DP';
function calibrateLeftTailCount(cfg, epochs, windowNonces, z = exports.Z_LEFT_TAIL) {
    const byKey = new Map();
    for (const e of epochs) {
        const key = `${e.rows}/${e.riskLevel}`;
        const arr = byKey.get(key) ?? [];
        arr.push(e);
        byKey.set(key, arr);
    }
    const byConfig = [];
    const probByKey = new Map();
    const ordered = [...byKey.entries()].sort((a, b) => (a[1][0].rows - b[1][0].rows) || (a[1][0].riskLevel - b[1][0].riskLevel));
    for (const [key, group] of ordered) {
        const { rows, riskLevel } = group[0];
        const dist = payoutValueDistribution(cfg, rows, riskLevel);
        const { mu, sd } = payoutMuSd(cfg, rows, riskLevel);
        const sumThreshold = leftTailSumThreshold(mu, sd, windowNonces, z);
        const exact = exactLeftTailProbability(dist, windowNonces, sumThreshold);
        const alt = enumerationLeftTailProbability(dist, windowNonces, sumThreshold);
        byConfig.push({
            config: key,
            rows,
            riskLevel,
            epochs: group.length,
            mu,
            sd,
            windowNonces,
            sumThreshold,
            windowRtpThreshold: sumThreshold / windowNonces,
            latticeUnit: exact.latticeUnit,
            leftTailProbability: exact.probability,
            crossCheck: alt === null ? null : {
                method: 'closed-form multinomial enumeration over the non-minimum payout counts',
                probability: alt,
                relativeDifference: alt === 0 ? (exact.probability === 0 ? 0 : Infinity) : (exact.probability - alt) / alt,
            },
        });
        probByKey.set(key, exact.probability);
    }
    const perEpoch = epochs.map(e => ({
        ...e,
        leftTailProbability: probByKey.get(`${e.rows}/${e.riskLevel}`),
    }));
    const ps = perEpoch.map(e => e.leftTailProbability);
    const expectation = ps.reduce((s, p) => s + p, 0);
    const variance = ps.reduce((s, p) => s + p * (1 - p), 0);
    return {
        method: exports.CALIBRATION_METHOD,
        zThreshold: z,
        windowNonces,
        epochs: epochs.length,
        expectedZEarlyBelow1645Calibrated: expectation,
        varianceCalibrated: variance,
        sdCalibrated: Math.sqrt(variance),
        expectedZEarlyBelow1645Naive: epochs.length * 0.05,
        byConfig,
        perEpoch,
    };
}
function calibratedSurvival(calibration, observedCount) {
    return poissonBinomialSurvival(calibration.perEpoch.map(e => e.leftTailProbability), observedCount);
}

},
"src/config.js": function(module, exports, require, __filename, __dirname) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.riskName = exports.slotCount = exports.isWtf = exports.WTF_RISK = exports.PASS2_NONCES_PUBLISHED = exports.CONVERGENCE_STEP = exports.PLINKO_CONFIG_SHA256 = void 0;
exports.configSha256 = configSha256;
exports.loadPlinkoConfig = loadPlinkoConfig;
exports.payoutTable = payoutTable;
exports.payoutMultiplier = payoutMultiplier;
exports.binomP = binomP;
exports.theoreticalRTP = theoreticalRTP;
exports.allConfigs = allConfigs;
const node_fs_1 = require("node:fs");
const node_crypto_1 = require("node:crypto");
const node_path_1 = require("node:path");
const CONFIG_PATH = (0, node_path_1.join)(__dirname, '..', 'plinkoConfig.json');
exports.PLINKO_CONFIG_SHA256 = 'f8eaf67e1ffc63ee0dc21123447581c55f443c167dcb451b45ab7cd108fe712f';
function configSha256() {
    return (0, node_crypto_1.createHash)('sha256').update((0, node_fs_1.readFileSync)(CONFIG_PATH)).digest('hex');
}
function loadPlinkoConfig(expected = exports.PLINKO_CONFIG_SHA256) {
    if (!(0, node_fs_1.existsSync)(CONFIG_PATH)) {
        console.error(`ERROR: plinko config not found at ${CONFIG_PATH}`);
        process.exit(1);
    }
    const raw = (0, node_fs_1.readFileSync)(CONFIG_PATH);
    const sha256 = (0, node_crypto_1.createHash)('sha256').update(raw).digest('hex');
    if (expected && sha256 !== expected) {
        console.error('ERROR: plinkoConfig.json SHA-256 mismatch — table differs from the audited artifact');
        console.error(`  expected: ${expected}`);
        console.error(`  actual:   ${sha256}`);
        process.exit(1);
    }
    return JSON.parse(raw.toString('utf8'));
}
exports.CONVERGENCE_STEP = 50000;
exports.PASS2_NONCES_PUBLISHED = 10000;
exports.WTF_RISK = 4;
const isWtf = (riskLevel) => riskLevel === exports.WTF_RISK;
exports.isWtf = isWtf;
const slotCount = (rows) => rows + 1;
exports.slotCount = slotCount;
function payoutTable(cfg, rows, riskLevel) {
    if ((0, exports.isWtf)(riskLevel)) {
        if (rows !== cfg.wtf_mode.rows)
            throw new Error(`WTF rows must be ${cfg.wtf_mode.rows}, got ${rows}`);
        return cfg.wtf_mode.odds;
    }
    const bucket = cfg.payout_tables[String(rows)];
    if (!bucket)
        throw new Error(`rows=${rows} not in config`);
    const arr = bucket[riskLevel - 1];
    if (!arr)
        throw new Error(`riskLevel=${riskLevel} not in config for rows=${rows}`);
    return arr;
}
function payoutMultiplier(cfg, rows, riskLevel, slot) {
    return payoutTable(cfg, rows, riskLevel)[slot];
}
function binomP(rows, k) {
    let c = 1;
    for (let i = 0; i < k; i++)
        c = (c * (rows - i)) / (i + 1);
    return c * Math.pow(0.5, rows);
}
function theoreticalRTP(cfg, rows, riskLevel) {
    const t = payoutTable(cfg, rows, riskLevel);
    let rtp = 0;
    for (let k = 0; k <= rows; k++)
        rtp += binomP(rows, k) * t[k];
    return rtp;
}
function allConfigs(cfg, includeWtf = true) {
    const out = [];
    for (let rows = cfg.rows.min; rows <= cfg.rows.max; rows++)
        for (const r of [1, 2, 3])
            out.push({ rows, riskLevel: r });
    if (includeWtf)
        out.push({ rows: cfg.wtf_mode.rows, riskLevel: cfg.wtf_mode.riskLevel });
    return out;
}
const riskName = (cfg, riskLevel) => cfg.riskLevels[String(riskLevel)] ?? `risk${riskLevel}`;
exports.riskName = riskName;

},
"src/domains.js": function(module, exports, require, __filename, __dirname) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.realBetween = exports.intBetween = exports.intAtMost = exports.CHI_SQUARED = exports.PERCENT = exports.CORRELATION = exports.PROBABILITY = exports.NONNEG_INT = exports.POSITIVE_REAL = exports.NONNEG_REAL = exports.FINITE = void 0;
exports.attainableMultiplierRange = attainableMultiplierRange;
exports.boardMultiplierRange = boardMultiplierRange;
exports.pass2WindowDrops = pass2WindowDrops;
exports.totalPayoutCells = totalPayoutCells;
exports.collapsePath = collapsePath;
exports.domainRules = domainRules;
exports.numericLeaves = numericLeaves;
exports.validateDomains = validateDomains;
exports.describeDomainFailures = describeDomainFailures;
const config_1 = require("./config");
const loader_1 = require("./loader");
const D = (label, ok) => ({ label, ok });
exports.FINITE = D('a finite number', v => Number.isFinite(v));
exports.NONNEG_REAL = D('a non-negative real', v => Number.isFinite(v) && v >= 0);
exports.POSITIVE_REAL = D('a strictly positive real', v => Number.isFinite(v) && v > 0);
exports.NONNEG_INT = D('a non-negative integer', v => Number.isInteger(v) && v >= 0);
exports.PROBABILITY = D('a probability in [0,1]', v => Number.isFinite(v) && v >= 0 && v <= 1);
exports.CORRELATION = D('a correlation in [-1,1]', v => Number.isFinite(v) && v >= -1 && v <= 1);
exports.PERCENT = D('a percentage in [0,100]', v => Number.isFinite(v) && v >= 0 && v <= 100);
exports.CHI_SQUARED = D('a non-negative chi-squared statistic', v => Number.isFinite(v) && v >= 0);
const intAtMost = (max, what) => D(`an integer in [0, ${max}] (${what})`, v => Number.isInteger(v) && v >= 0 && v <= max);
exports.intAtMost = intAtMost;
const intBetween = (lo, hi, what) => D(`an integer in [${lo}, ${hi}] (${what})`, v => Number.isInteger(v) && v >= lo && v <= hi);
exports.intBetween = intBetween;
const realBetween = (lo, hi, what) => D(`a real in [${lo}, ${hi}] (${what})`, v => Number.isFinite(v) && v >= lo && v <= hi);
exports.realBetween = realBetween;
function attainableMultiplierRange(cfg) {
    let min = Infinity;
    let max = -Infinity;
    for (const c of (0, config_1.allConfigs)(cfg)) {
        for (const m of (0, config_1.payoutTable)(cfg, c.rows, c.riskLevel)) {
            if (m < min)
                min = m;
            if (m > max)
                max = m;
        }
    }
    return { min, max };
}
function boardMultiplierRange(cfg, rows, riskLevel) {
    const table = (0, config_1.payoutTable)(cfg, rows, riskLevel);
    return { min: Math.min(...table), max: Math.max(...table) };
}
function pass2WindowDrops() {
    return loader_1.EXPECTED_SEEDS * Math.floor(config_1.PASS2_NONCES_PUBLISHED / 2);
}
function totalPayoutCells(cfg) {
    return (0, config_1.allConfigs)(cfg).reduce((s, c) => s + (0, config_1.slotCount)(c.rows), 0);
}
function collapsePath(path) {
    return path.replace(/\[\d+\]/g, '[]');
}
function domainRules(cfg) {
    const configs = (0, config_1.allConfigs)(cfg).length;
    const cells = totalPayoutCells(cfg);
    const { min: mMin, max: mMax } = attainableMultiplierRange(cfg);
    const RTP = (0, exports.realBetween)(mMin, mMax, 'attainable multiplier range of the pinned paytable');
    const ROWS = (0, exports.intBetween)(cfg.rows.min, cfg.rows.max, 'declared board sizes');
    const RISK = (0, exports.intBetween)(1, cfg.wtf_mode.riskLevel, 'declared risk levels');
    const EPOCH_IDX = (0, exports.intAtMost)(loader_1.EXPECTED_SEEDS - 1, 'epoch index within the audited population');
    const SEED_COUNT = (0, exports.intAtMost)(loader_1.EXPECTED_SEEDS, 'audited seed population');
    const BET_COUNT = (0, exports.intAtMost)(loader_1.EXPECTED_BETS, 'audited bet population');
    const CFG_COUNT = (0, exports.intAtMost)(configs, 'configurations the pinned config declares');
    const CELL_COUNT = (0, exports.intAtMost)(cells, 'paytable cells the pinned config declares');
    const SLOTS = (0, exports.intBetween)((0, config_1.slotCount)(cfg.rows.min), (0, config_1.slotCount)(cfg.rows.max), 'slots per board');
    const EDGE_HITS = (0, exports.intAtMost)(pass2WindowDrops(), 'drops in one Pass-2 window across the audited seed population');
    return {
        'simulation-results.json': [
            { path: /^\.houseEdge$/, domain: exports.PROBABILITY },
            { path: /^\.pass1_fresh_seeds\.(configs)$/, domain: CFG_COUNT },
            { path: /^\.pass1_fresh_seeds\.(roundsPerConfig|totalRounds)$/, domain: exports.NONNEG_INT },
            { path: /^\.pass1_fresh_seeds\.executionTimeMs$/, domain: exports.NONNEG_REAL },
            { path: /^\.pass1_fresh_seeds\.(chi2FailsAtAlpha01|chi2FailsBonferroni|serialIndependenceFailsUncorrected|serialIndependenceFailsBonferroni)$/, domain: CFG_COUNT },
            { path: /^\.pass1_fresh_seeds\.bonferroniAlpha$/, domain: exports.PROBABILITY },
            { path: /^\.pass1_fresh_seeds\.bonferroniZCritical$/, domain: exports.NONNEG_REAL },
            { path: /^\.pass1_fresh_seeds\.(meanSimulatedRTP|meanTheoreticalRTP)$/, domain: RTP },
            { path: /^\.pass1_fresh_seeds\.results\[\]\.rows$/, domain: ROWS },
            { path: /^\.pass1_fresh_seeds\.results\[\]\.riskLevel$/, domain: RISK },
            { path: /^\.pass1_fresh_seeds\.results\[\]\.slotChi2$/, domain: exports.CHI_SQUARED },
            { path: /^\.pass1_fresh_seeds\.results\[\]\.slotDf$/, domain: exports.NONNEG_INT },
            { path: /^\.pass1_fresh_seeds\.results\[\]\.(slotPValue|runsPValue)$/, domain: exports.PROBABILITY },
            { path: /^\.pass1_fresh_seeds\.results\[\]\.r1$/, domain: exports.CORRELATION },
            { path: /^\.pass1_fresh_seeds\.results\[\]\.(r1Z|runsZ)$/, domain: exports.FINITE },
            { path: /^\.pass1_fresh_seeds\.results\[\]\.(theoreticalRTP|simRTP)$/, domain: RTP },
            { path: /^\.pass1_fresh_seeds\.results\[\]\.convergence\[\]$/, domain: RTP },
            { path: /^\.pass2_casino_seeds\.noncesPerSeed$/, domain: exports.NONNEG_INT },
            { path: /^\.pass2_casino_seeds\.seeds_tested$/, domain: SEED_COUNT },
            { path: /^\.pass2_casino_seeds\.cherryPickFlags$/, domain: SEED_COUNT },
            { path: /^\.pass2_casino_seeds\.expectedFlagsByChance$/, domain: (0, exports.realBetween)(0, loader_1.EXPECTED_SEEDS, 'expected count over the seed population') },
            { path: /^\.pass2_casino_seeds\.cherryPickSurvivalP$/, domain: exports.PROBABILITY },
            { path: /^\.pass2_casino_seeds\.executionTimeMs$/, domain: exports.NONNEG_REAL },
            { path: /^\.pass2_casino_seeds\.payoutWeighted\.(zEarlyMean|meanZEarlyMinusLate|tZEarlyMinusLate)$/, domain: exports.FINITE },
            { path: /^\.pass2_casino_seeds\.payoutWeighted\.(zEarlySd|seZEarlyMinusLate)$/, domain: exports.NONNEG_REAL },
            { path: /^\.pass2_casino_seeds\.payoutWeighted\.countZEarlyBelow1645$/, domain: SEED_COUNT },
            { path: /^\.pass2_casino_seeds\.payoutWeighted\.expectedZEarlyBelow1645$/, domain: (0, exports.realBetween)(0, loader_1.EXPECTED_SEEDS, 'expected count over the seed population') },
            { path: /^\.pass2_casino_seeds\.payoutWeighted\.(zEarlyBelowSurvivalP|pTwoSidedZEarlyMinusLate)$/, domain: exports.PROBABILITY },
            { path: /^\.pass2_casino_seeds\.payoutWeighted\.(edgeHitsEarly|edgeHitsLate)$/, domain: EDGE_HITS },
            { path: /^\.pass2_casino_seeds\.results\[\]\.epoch$/, domain: EPOCH_IDX },
            { path: /^\.pass2_casino_seeds\.results\[\]\.rows$/, domain: ROWS },
            { path: /^\.pass2_casino_seeds\.results\[\]\.riskLevel$/, domain: RISK },
            { path: /^\.pass2_casino_seeds\.results\[\]\.(earlyPValue|latePValue)$/, domain: exports.PROBABILITY },
            { path: /^\.pass2_casino_seeds\.results\[\]\.(zEarly|zLate)$/, domain: exports.FINITE },
            { path: /^\.pass2_casino_seeds\.results\[\]\.(rtpEarly|rtpLate)$/, domain: RTP },
        ],
        'calibration-results.json': [
            { path: /^\.zThreshold$/, domain: exports.NONNEG_REAL },
            { path: /^\.(noncesPerSeed|windowNonces)$/, domain: exports.NONNEG_INT },
            { path: /^\.epochs$/, domain: SEED_COUNT },
            { path: /^\.(expectedZEarlyBelow1645Calibrated|expectedZEarlyBelow1645Naive)$/, domain: (0, exports.realBetween)(0, loader_1.EXPECTED_SEEDS, 'expected count over the seed population') },
            { path: /^\.(sdZEarlyBelow1645Calibrated|varianceZEarlyBelow1645Calibrated)$/, domain: exports.NONNEG_REAL },
            { path: /^\.observedZEarlyBelow1645$/, domain: SEED_COUNT },
            { path: /^\.zEarlyBelowCalibratedSurvivalP$/, domain: exports.PROBABILITY },
            { path: /^\.executionTimeMs$/, domain: exports.NONNEG_REAL },
            { path: /^\.byConfig\[\]\.rows$/, domain: ROWS },
            { path: /^\.byConfig\[\]\.riskLevel$/, domain: RISK },
            { path: /^\.byConfig\[\]\.epochs$/, domain: SEED_COUNT },
            { path: /^\.byConfig\[\]\.mu$/, domain: RTP },
            { path: /^\.byConfig\[\]\.sd$/, domain: exports.NONNEG_REAL },
            { path: /^\.byConfig\[\]\.windowNonces$/, domain: exports.NONNEG_INT },
            { path: /^\.byConfig\[\]\.sumThreshold$/, domain: exports.FINITE },
            { path: /^\.byConfig\[\]\.windowRtpThreshold$/, domain: RTP },
            { path: /^\.byConfig\[\]\.latticeUnit$/, domain: exports.POSITIVE_REAL },
            { path: /^\.byConfig\[\]\.leftTailProbability$/, domain: exports.PROBABILITY },
            { path: /^\.byConfig\[\]\.crossCheck\.probability$/, domain: exports.PROBABILITY },
            { path: /^\.byConfig\[\]\.crossCheck\.relativeDifference$/, domain: exports.FINITE },
            { path: /^\.perEpoch\[\]\.epoch$/, domain: EPOCH_IDX },
            { path: /^\.perEpoch\[\]\.rows$/, domain: ROWS },
            { path: /^\.perEpoch\[\]\.riskLevel$/, domain: RISK },
            { path: /^\.perEpoch\[\]\.leftTailProbability$/, domain: exports.PROBABILITY },
        ],
        'coverage-results.json': [
            { path: /^\.totalConfigs$/, domain: CFG_COUNT },
            { path: /^\.totalCells$/, domain: CELL_COUNT },
            { path: /^\.(cellsExercised|cellsUnexercised)$/, domain: CELL_COUNT },
            { path: /^\.coveragePct$/, domain: exports.PERCENT },
            { path: /^\.rtpShareUnexercisedSummed$/, domain: exports.NONNEG_REAL },
            { path: /^\.configsWithUnhitCells$/, domain: CFG_COUNT },
            { path: /^\.perConfig\[\]\.rows$/, domain: ROWS },
            { path: /^\.perConfig\[\]\.riskLevel$/, domain: RISK },
            { path: /^\.perConfig\[\]\.slots$/, domain: SLOTS },
            { path: /^\.perConfig\[\]\.observed\[\]$/, domain: BET_COUNT },
            { path: /^\.perConfig\[\]\.exercised$/, domain: (0, exports.intAtMost)((0, config_1.slotCount)(cfg.rows.max), 'slots on the largest declared board') },
            { path: /^\.perConfig\[\]\.unhit\[\]$/, domain: (0, exports.intAtMost)((0, config_1.slotCount)(cfg.rows.max) - 1, 'slot index on the largest declared board') },
            { path: /^\.perConfig\[\]\.rtpShareUnexercised$/, domain: exports.NONNEG_REAL },
        ],
        'verification-stats.json': [
            { path: /^\.steps\.step6\.(tested|expectedTested|changed|samePath)$/, domain: BET_COUNT },
            { path: /^\.steps\.step6\.expectedSamePath$/, domain: exports.NONNEG_REAL },
            { path: /^\.steps\.step6\.(samePathSurvivalP|alpha)$/, domain: exports.PROBABILITY },
            { path: /^\.steps\.step7\.(betsChecked|mismatches)$/, domain: BET_COUNT },
            { path: /^\.steps\.step7\.(cellsExercised|cellsTotal|cellsUnexercised)$/, domain: CELL_COUNT },
            { path: /^\.steps\.step10\.configs$/, domain: CFG_COUNT },
            { path: /^\.steps\.step10\.(minRTP|maxRTP)$/, domain: RTP },
            { path: /^\.steps\.step10\.(minEdge|maxEdge|maxDeviationFrom99)$/, domain: exports.FINITE },
            { path: /^\.steps\.step10\.(enumerationWorstDelta|enumerationTolerance)$/, domain: exports.NONNEG_REAL },
            { path: /^\.steps\.step11\.(betsLoaded|expectedBets|planSum|metaPlannedTotal)$/, domain: BET_COUNT },
            { path: /^\.steps\.step11\.(seedRecords|expectedSeeds)$/, domain: SEED_COUNT },
            { path: /^\.steps\.step11\.(phaseCounts|expectedPhaseBets)\.[A-E]$/, domain: BET_COUNT },
            { path: /^\.steps\.step12\.(epochsByHash|epochIndexes|expectedSeeds|seedRecords)$/, domain: SEED_COUNT },
            { path: /^\.steps\.step12\.(minEpochSize|maxEpochSize|expectedEpochSize|metaEpochSize)$/, domain: (0, exports.intAtMost)(loader_1.EXPECTED_BETS, 'bets in an epoch') },
            { path: /^\.steps\.step14\.(phaseDBets|recomputed|exposedBets)$/, domain: BET_COUNT },
            { path: /^\.steps\.step14\.distinctClientSeeds$/, domain: BET_COUNT },
            { path: /^\.steps\.step14\.(phaseDWagered|phaseDPaid|exposedWagered|exposedPaid)$/, domain: exports.NONNEG_REAL },
            { path: /^\.steps\.step14\.(predictableEpochs\[\]|exposedEpochs\[\])$/, domain: EPOCH_IDX },
            { path: /^\.steps\.step14\.unresolvedPredictabilityEpoch$/, domain: (0, exports.intBetween)(-1, loader_1.EXPECTED_SEEDS - 1, 'epoch index, or -1 for none') },
            { path: /^\.steps\.step15\.(wtfBets|recomputed|multipliersChecked)$/, domain: BET_COUNT },
            { path: /^\.steps\.step15\.wtfTheoreticalRTP$/, domain: RTP },
            { path: /^\.steps\.step15\.(payingSlots|totalSlots)$/, domain: (0, exports.intAtMost)((0, config_1.slotCount)(cfg.rows.max), 'slots on a board') },
            { path: /^\.steps\.step15\.(pZeroPayout|pPayingSlot)$/, domain: exports.PROBABILITY },
            { path: /^\.steps\.step16\.(expectedConfigs|resultRows|boardsPresentExactlyOnce|missingConfigs|strangerConfigs|duplicateConfigs|chi2BonferroniFails|serialUncorrectedFails|serialBonferroniFails|rtpWithin6SE|theoryRowsAgreeingWithPinnedConfig|serialPairsMeasured|aggregateDisagreements)$/, domain: CFG_COUNT },
            { path: /^\.steps\.step16\.(roundsPerConfig|totalRounds)$/, domain: exports.NONNEG_INT },
            { path: /^\.steps\.step16\.(bonferroniAlpha|theoryRecomputeTolerance)$/, domain: exports.PROBABILITY },
            { path: /^\.steps\.step16\.serialR1ZRunsZCorrelation$/, domain: exports.CORRELATION },
            { path: /^\.steps\.step16\.serialR1ZRunsZCorrelationAbs$/, domain: (0, exports.realBetween)(0, 1, 'absolute correlation') },
            { path: /^\.steps\.step16\.serialMaxAbsR1ZPlusRunsZ$/, domain: exports.NONNEG_REAL },
            { path: /^\.steps\.step17\.(attestChecked|attestPopulation|revealedEpochs|missingRows|seedsTested|revealedSeedCount|resultRows|cherryPickFlags|countZEarlyBelow1645)$/, domain: SEED_COUNT },
            { path: /^\.steps\.step17\.attestMaxAbsDiff$/, domain: exports.NONNEG_REAL },
            { path: /^\.steps\.step17\.(noncesPerSeed|windowNonces)$/, domain: exports.NONNEG_INT },
            { path: /^\.steps\.step17\.calibratedExpectation$/, domain: (0, exports.realBetween)(0, loader_1.EXPECTED_SEEDS, 'expected count over the seed population') },
            { path: /^\.steps\.step17\.calibratedSurvivalP$/, domain: exports.PROBABILITY },
            { path: /^\.steps\.step17\.rtpRowsRecomputed$/, domain: SEED_COUNT },
            { path: /^\.steps\.step17\.(recomputedEdgeHitsEarly|recomputedEdgeHitsLate)$/, domain: EDGE_HITS },
            { path: /^\.steps\.step17\.summaryFieldsRecomputed$/, domain: exports.NONNEG_INT },
            { path: /^\.steps\.step(16|17|20)\.(domainLeavesChecked|domainViolations|domainUndeclaredFields|domainFailures)$/, domain: exports.NONNEG_INT },
            { path: /^\.steps\.step21\.drops$/, domain: BET_COUNT },
            { path: /^\.steps\.step21\.seeds$/, domain: SEED_COUNT },
            { path: /^\.steps\.step21\.groups$/, domain: CFG_COUNT },
            { path: /^\.steps\.step21\.(fisherX2|perGroupChi2\.rows\d+)$/, domain: exports.CHI_SQUARED },
            { path: /^\.steps\.step21\.fisherDf$/, domain: exports.NONNEG_INT },
            { path: /^\.steps\.step21\.(fisherCombinedP|minGroupP|bonferroniPerGroupAlpha|perGroupP\.rows\d+)$/, domain: exports.PROBABILITY },
            { path: /^\.steps\.step21\.perGroupN\.rows\d+$/, domain: BET_COUNT },
            { path: /^\.info\.Live RTP\.liveRTP$/, domain: RTP },
            { path: /^\.info\.Live RTP\.(totalWagered|totalPayout)$/, domain: exports.NONNEG_REAL },
            { path: /^\.info\.Live RTP\.bets$/, domain: BET_COUNT },
            { path: /^\.info\.Lag-1 autocorr\.lag1Autocorrelation$/, domain: exports.CORRELATION },
            { path: /^\.info\.Lag-1 autocorr\.sequenceLength$/, domain: BET_COUNT },
            { path: /^\.info\.Win rate by config\.configs$/, domain: CFG_COUNT },
            { path: /^\.info\.Win rate by config\.(strictlyProfitable(Min|Max)Pct|resultWon(Min|Max)Pct)$/, domain: exports.PERCENT },
            { path: /^\.info\.Slot distribution\.maxSlotDeviation\.rows\d+$/, domain: exports.NONNEG_REAL },
            { path: /^\.info\.Slot distribution\.groupN\.rows\d+$/, domain: BET_COUNT },
        ],
    };
}
function numericLeaves(doc, path = '', out = []) {
    if (typeof doc === 'number') {
        out.push([collapsePath(path), doc]);
        return out;
    }
    if (doc === null || typeof doc !== 'object')
        return out;
    if (Array.isArray(doc)) {
        doc.forEach((v, i) => numericLeaves(v, `${path}[${i}]`, out));
        return out;
    }
    for (const [k, v] of Object.entries(doc))
        numericLeaves(v, `${path}.${k}`, out);
    return out;
}
function validateDomains(doc, rules) {
    const violations = [];
    const uncovered = [];
    const leaves = numericLeaves(doc);
    for (const [p, v] of leaves) {
        const rule = rules.find(r => r.path.test(p));
        if (!rule) {
            if (!uncovered.includes(p))
                uncovered.push(p);
            continue;
        }
        if (!rule.domain.ok(v))
            violations.push({ path: p, value: v, expected: rule.domain.label });
    }
    return { violations, uncovered, checked: leaves.length };
}
function describeDomainFailures(artifact, r) {
    const out = [];
    for (const v of r.violations.slice(0, 4)) {
        out.push(`${artifact}${v.path} = ${v.value} is not ${v.expected}`);
    }
    if (r.violations.length > 4)
        out.push(`${artifact}: +${r.violations.length - 4} more impossible value(s)`);
    for (const p of r.uncovered.slice(0, 4)) {
        out.push(`${artifact}${p} has no declared value domain (add one in src/domains.ts)`);
    }
    if (r.uncovered.length > 4)
        out.push(`${artifact}: +${r.uncovered.length - 4} more undeclared field(s)`);
    return out;
}

},
"src/loader.js": function(module, exports, require, __filename, __dirname) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.EXPECTED_PHASE_BETS = exports.EXPECTED_EPOCH_SIZE = exports.EXPECTED_SEEDS = exports.EXPECTED_BETS = exports.EXPECTED_DATASET_SHA256 = void 0;
exports.loadDataset = loadDataset;
exports.revealedSeedMap = revealedSeedMap;
exports.seedByEpoch = seedByEpoch;
exports.betsByEpoch = betsByEpoch;
exports.phaseBets = phaseBets;
const node_crypto_1 = require("node:crypto");
const node_fs_1 = require("node:fs");
exports.EXPECTED_DATASET_SHA256 = '871c485ef0d55ca38af2cece4880abdc32fe8b62584468c5d4cfdfd01506fc95';
exports.EXPECTED_BETS = 10100;
exports.EXPECTED_SEEDS = 202;
exports.EXPECTED_EPOCH_SIZE = 50;
exports.EXPECTED_PHASE_BETS = { A: 5400, B: 2000, C: 200, D: 500, E: 2000 };
function loadDataset(path, expectedSha256) {
    if (!(0, node_fs_1.existsSync)(path)) {
        console.error(`ERROR: dataset not found at ${path}`);
        process.exit(1);
    }
    const raw = (0, node_fs_1.readFileSync)(path);
    const sha256 = (0, node_crypto_1.createHash)('sha256').update(raw).digest('hex');
    if (expectedSha256 && sha256 !== expectedSha256) {
        console.error(`ERROR: dataset SHA-256 mismatch`);
        console.error(`  expected: ${expectedSha256}`);
        console.error(`  actual:   ${sha256}`);
        process.exit(1);
    }
    const parsed = JSON.parse(raw.toString('utf8'));
    return { ...parsed, sha256, path };
}
function revealedSeedMap(seeds) {
    const m = new Map();
    for (const s of seeds)
        m.set(s.hashedServerSeed, s);
    return m;
}
function seedByEpoch(seeds) {
    const m = new Map();
    for (const s of seeds)
        m.set(s.epoch, s);
    return m;
}
function betsByEpoch(bets) {
    const m = new Map();
    for (const b of bets) {
        const a = m.get(b.epoch);
        if (a)
            a.push(b);
        else
            m.set(b.epoch, [b]);
    }
    return m;
}
function phaseBets(bets, phase) {
    return bets.filter((b) => b.phase === phase);
}

},
"src/rng.js": function(module, exports, require, __filename, __dirname) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.commitHash = commitHash;
exports.sha256Buffer = sha256Buffer;
exports.getProvablyFairHmacSalt = getProvablyFairHmacSalt;
exports.generateProvablyFairNumber = generateProvablyFairNumber;
exports.revealPlinko = revealPlinko;
const node_crypto_1 = require("node:crypto");
function commitHash(serverSeedHexString) {
    return (0, node_crypto_1.createHash)('sha256').update(serverSeedHexString, 'utf8').digest('hex');
}
function sha256Buffer(buf) {
    return (0, node_crypto_1.createHash)('sha256').update(buf).digest('hex');
}
function getProvablyFairHmacSalt(clientSeed, nonce, cursor) {
    return `${clientSeed}:${nonce}:${cursor}`;
}
function generateProvablyFairNumber(serverSeed, clientSeed, nonce, cursor, range) {
    const key = Buffer.from(serverSeed, 'hex');
    const digest = (0, node_crypto_1.createHmac)('sha256', key)
        .update(getProvablyFairHmacSalt(clientSeed, nonce, cursor))
        .digest();
    const maxFair = Math.floor(4294967296 / range) * range;
    for (let offset = 0; offset + 4 <= digest.length; offset += 4) {
        const chunk = digest.readUInt32BE(offset);
        if (chunk < maxFair)
            return chunk % range;
    }
    return generateProvablyFairNumber(serverSeed, clientSeed, nonce, cursor + 1000000, range);
}
function revealPlinko(serverSeed, clientSeed, nonce, numberOfRows) {
    let path = '';
    for (let i = 0; i < numberOfRows; i++) {
        const bit = generateProvablyFairNumber(serverSeed, clientSeed, nonce, i + 1, 2);
        path += `${bit}`;
    }
    const winningSlot = path.split('').filter((c) => c === '1').length;
    return { path, winningSlot };
}

},
"src/types.js": function(module, exports, require, __filename, __dirname) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });

},
"tests/plinko/calibrationTests.js": function(module, exports, require, __filename, __dirname) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const node_assert_1 = require("node:assert");
const node_crypto_1 = require("node:crypto");
const config_1 = require("../../src/config");
const calibration_1 = require("../../src/calibration");
const cfg = (0, config_1.loadPlinkoConfig)();
function bruteForceLeftTail(dist, n, threshold) {
    let acc = 0;
    const walk = (i, sum, p) => {
        if (i === n) {
            if (sum < threshold)
                acc += p;
            return;
        }
        for (const d of dist)
            walk(i + 1, sum + d.value, p * d.prob);
    };
    walk(0, 0, 1);
    return acc;
}
describe('calibration: exact left-tail DP vs brute-force enumeration', () => {
    const cases = [[8, 1, 6], [16, 3, 5], [13, 4, 7], [12, 2, 5], [14, 1, 5]];
    for (const [rows, risk, n] of cases) {
        const dist = (0, calibration_1.payoutValueDistribution)(cfg, rows, risk);
        const { mu } = (0, calibration_1.payoutMuSd)(cfg, rows, risk);
        for (const frac of [0.7, 0.9, 1.0, 1.15]) {
            const threshold = n * mu * frac;
            it(`rows ${rows} risk ${risk}, n=${n}, threshold ${frac}x mean`, () => {
                const brute = bruteForceLeftTail(dist, n, threshold);
                const dp = (0, calibration_1.exactLeftTailProbability)(dist, n, threshold).probability;
                node_assert_1.strict.ok(Math.abs(dp - brute) <= 1e-12 * Math.max(1, brute), `DP ${dp} != brute force ${brute}`);
            });
        }
    }
});
describe('calibration: WTF left tail at the production window, two algorithms', () => {
    const rows = cfg.wtf_mode.rows;
    const risk = cfg.wtf_mode.riskLevel;
    const n = 5000;
    const dist = (0, calibration_1.payoutValueDistribution)(cfg, rows, risk);
    const { mu, sd } = (0, calibration_1.payoutMuSd)(cfg, rows, risk);
    const threshold = (0, calibration_1.leftTailSumThreshold)(mu, sd, n, calibration_1.Z_LEFT_TAIL);
    it('the two algorithms agree to better than 1e-9 relative', () => {
        const dp = (0, calibration_1.exactLeftTailProbability)(dist, n, threshold).probability;
        const closed = (0, calibration_1.enumerationLeftTailProbability)(dist, n, threshold);
        node_assert_1.strict.ok(closed !== null, 'closed-form path should be available for a 3-value support');
        const rel = Math.abs(dp - closed) / closed;
        node_assert_1.strict.ok(rel < 1e-9, `relative difference ${rel} between DP ${dp} and closed form ${closed}`);
    });
    it('the WTF left tail is far below the naive 0.05 — this is the whole point', () => {
        const dp = (0, calibration_1.exactLeftTailProbability)(dist, n, threshold).probability;
        node_assert_1.strict.ok(dp > 0.02 && dp < 0.03, `WTF left tail ${dp} outside the expected 2-3% band`);
    });
});
describe('calibration: Monte-Carlo cross-check at the production window', () => {
    const SCALE = 2 ** 32;
    function makeUniformStream() {
        const buf = new Uint32Array(1 << 16);
        let i = buf.length;
        return () => {
            if (i >= buf.length) {
                (0, node_crypto_1.randomFillSync)(buf);
                i = 0;
            }
            return buf[i++] / SCALE;
        };
    }
    function monteCarloLeftTail(rows, risk, n, replicates) {
        const dist = (0, calibration_1.payoutValueDistribution)(cfg, rows, risk);
        const { mu, sd } = (0, calibration_1.payoutMuSd)(cfg, rows, risk);
        const threshold = (0, calibration_1.leftTailSumThreshold)(mu, sd, n, calibration_1.Z_LEFT_TAIL);
        const dp = (0, calibration_1.exactLeftTailProbability)(dist, n, threshold).probability;
        const cum = [];
        const vals = [];
        let acc = 0;
        for (const d of dist) {
            acc += d.prob;
            cum.push(acc);
            vals.push(d.value);
        }
        cum[cum.length - 1] = 1;
        const nextU = makeUniformStream();
        let hits = 0;
        for (let r = 0; r < replicates; r++) {
            let sum = 0;
            for (let i = 0; i < n; i++) {
                const u = nextU();
                let j = 0;
                while (u > cum[j])
                    j++;
                sum += vals[j];
            }
            if (sum < threshold)
                hits++;
        }
        const pHat = hits / replicates;
        return { pHat, se: Math.sqrt(Math.max(pHat, 1 / replicates) * (1 - pHat) / replicates), dp };
    }
    for (const [rows, risk, replicates] of [[8, 1, 150000], [16, 3, 100000]]) {
        it(`rows ${rows} risk ${risk}: DP within 5 SE of ${replicates.toLocaleString()} simulated 5,000-nonce windows`, function () {
            this.timeout(600000);
            const { pHat, se, dp } = monteCarloLeftTail(rows, risk, 5000, replicates);
            node_assert_1.strict.ok(Math.abs(dp - pHat) <= 5 * se, `exact ${dp} vs Monte-Carlo ${pHat} +/- ${se} (${Math.abs(dp - pHat) / se} SE)`);
        });
    }
});
describe('calibration: Poisson-binomial aggregation', () => {
    it('pmf is a distribution and reproduces the binomial when all p are equal', () => {
        const ps = new Array(20).fill(0.05);
        const pmf = (0, calibration_1.poissonBinomialPmf)(ps);
        const total = [...pmf].reduce((s, v) => s + v, 0);
        node_assert_1.strict.ok(Math.abs(total - 1) < 1e-12, `pmf sums to ${total}`);
        node_assert_1.strict.ok(Math.abs(pmf[0] - Math.pow(0.95, 20)) < 1e-12);
        const mean = [...pmf].reduce((s, v, k) => s + k * v, 0);
        node_assert_1.strict.ok(Math.abs(mean - 1) < 1e-12, `mean ${mean}`);
    });
    it('survival is monotone and bounded', () => {
        const ps = [0.1, 0.2, 0.3, 0.4];
        node_assert_1.strict.ok(Math.abs((0, calibration_1.poissonBinomialSurvival)(ps, 0) - 1) < 1e-12);
        node_assert_1.strict.ok((0, calibration_1.poissonBinomialSurvival)(ps, 1) > (0, calibration_1.poissonBinomialSurvival)(ps, 2));
        node_assert_1.strict.ok((0, calibration_1.poissonBinomialSurvival)(ps, 5) === 0);
    });
});
describe('calibration: the guard can fail (known-bad values)', () => {
    const epochs = (0, config_1.allConfigs)(cfg).map((c, i) => ({ epoch: i, rows: c.rows, riskLevel: c.riskLevel }));
    let cal;
    before(function () {
        this.timeout(600000);
        cal = (0, calibration_1.calibrateLeftTailCount)(cfg, epochs, 1000, calibration_1.Z_LEFT_TAIL);
    });
    it('the calibrated expectation is materially below the naive 0.05·n it replaced', () => {
        node_assert_1.strict.ok(cal.expectedZEarlyBelow1645Calibrated < 0.9 * cal.expectedZEarlyBelow1645Naive, `calibrated ${cal.expectedZEarlyBelow1645Calibrated} is not below naive ${cal.expectedZEarlyBelow1645Naive}`);
    });
    it('an impossible count has survival 0 — a fabricated high count cannot pass the gate', () => {
        const ps = cal.perEpoch.map(e => e.leftTailProbability);
        node_assert_1.strict.equal((0, calibration_1.poissonBinomialSurvival)(ps, epochs.length + 1), 0);
        node_assert_1.strict.ok((0, calibration_1.poissonBinomialSurvival)(ps, Math.ceil(cal.expectedZEarlyBelow1645Calibrated) + 12) < 0.01);
    });
    it('a payout value off the 0.1 lattice is rejected, not silently rounded', () => {
        const bad = [{ value: 0.25, prob: 0.5 }, { value: 1.75, prob: 0.5 }];
        node_assert_1.strict.throws(() => (0, calibration_1.exactLeftTailProbability)(bad, 10, 5), /not a multiple of/);
    });
    it('a threshold below the minimum attainable sum gives probability 0', () => {
        const dist = (0, calibration_1.payoutValueDistribution)(cfg, 16, 3);
        node_assert_1.strict.equal((0, calibration_1.exactLeftTailProbability)(dist, 100, 19.9).probability, 0);
    });
});

},
"tests/plinko/domainTests.js": function(module, exports, require, __filename, __dirname) {
"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
const assert_1 = require("assert");
const fs_1 = require("fs");
const path = __importStar(require("path"));
const config_1 = require("../../src/config");
const domains_1 = require("../../src/domains");
const cfg = (0, config_1.loadPlinkoConfig)();
const OUTPUTS = path.join(__dirname, '../../outputs');
const ARTIFACTS = [
    'simulation-results.json',
    'calibration-results.json',
    'coverage-results.json',
    'verification-stats.json',
];
describe('value domains: the committed artifacts are all inside their declared domains', () => {
    const rules = (0, domains_1.domainRules)(cfg);
    for (const name of ARTIFACTS) {
        it(`${name} — every numeric leaf satisfies its domain, and every leaf has one`, function () {
            const p = path.join(OUTPUTS, name);
            if (!(0, fs_1.existsSync)(p))
                this.skip();
            const doc = JSON.parse((0, fs_1.readFileSync)(p, 'utf8'));
            const r = (0, domains_1.validateDomains)(doc, rules[name]);
            assert_1.strict.equal(r.violations.length, 0, `committed ${name} carries value(s) outside their physical domain — either the artifact is wrong or the rule is too tight:\n  `
                + r.violations.slice(0, 10).map(v => `${v.path} = ${v.value} is not ${v.expected}`).join('\n  '));
            assert_1.strict.equal(r.uncovered.length, 0, `committed ${name} has numeric field(s) with NO declared value domain — declare them in src/domains.ts:\n  `
                + r.uncovered.slice(0, 10).join('\n  '));
            assert_1.strict.ok(r.checked > 0, `${name}: no numeric leaves were checked, so this assertion proved nothing`);
        });
    }
});
describe('value domains: impossible values are rejected', () => {
    const rules = (0, domains_1.domainRules)(cfg);
    it('a negative count of configurations is rejected (the executed QA-13 probe)', () => {
        const p = path.join(OUTPUTS, 'coverage-results.json');
        const doc = JSON.parse((0, fs_1.readFileSync)(p, 'utf8'));
        doc.totalConfigs = -1;
        const r = (0, domains_1.validateDomains)(doc, rules['coverage-results.json']);
        assert_1.strict.ok(r.violations.some(v => v.path === '.totalConfigs'), 'totalConfigs = -1 was accepted; a negative count of configurations is physically impossible');
    });
    it('a probability above 1 is rejected', () => {
        const p = path.join(OUTPUTS, 'calibration-results.json');
        const doc = JSON.parse((0, fs_1.readFileSync)(p, 'utf8'));
        doc.byConfig[0].leftTailProbability = 1.5;
        const r = (0, domains_1.validateDomains)(doc, rules['calibration-results.json']);
        assert_1.strict.ok(r.violations.some(v => v.path === '.byConfig[].leftTailProbability'), 'a left-tail probability of 1.5 was accepted');
    });
    it('an RTP outside the paytable\'s attainable range is rejected', () => {
        const { max } = (0, domains_1.attainableMultiplierRange)(cfg);
        const p = path.join(OUTPUTS, 'simulation-results.json');
        const doc = JSON.parse((0, fs_1.readFileSync)(p, 'utf8'));
        doc.pass1_fresh_seeds.results[0].simRTP = max + 1;
        const r = (0, domains_1.validateDomains)(doc, rules['simulation-results.json']);
        assert_1.strict.ok(r.violations.some(v => v.path === '.pass1_fresh_seeds.results[].simRTP'), `a simulated RTP of ${max + 1} was accepted, above the largest multiplier the pinned paytable contains (${max})`);
    });
    it('an edge-hit count above the drops a window contains is rejected (the executed QA-16 probe)', () => {
        const p = path.join(OUTPUTS, 'simulation-results.json');
        const doc = JSON.parse((0, fs_1.readFileSync)(p, 'utf8'));
        doc.pass2_casino_seeds.payoutWeighted.edgeHitsEarly = 1000000000;
        const r = (0, domains_1.validateDomains)(doc, rules['simulation-results.json']);
        assert_1.strict.ok(r.violations.some(v => v.path === '.pass2_casino_seeds.payoutWeighted.edgeHitsEarly'), `edgeHitsEarly = 1,000,000,000 was accepted; one Pass-2 window contains only ${(0, domains_1.pass2WindowDrops)()} drops`);
    });
    it('a window RTP below the board\'s smallest multiplier is rejected by the per-board range', () => {
        const { min, max } = (0, domains_1.boardMultiplierRange)(cfg, 8, 1);
        assert_1.strict.equal(min, 0.5);
        assert_1.strict.equal(max, 5.6);
        assert_1.strict.ok(0 < min, 'a 0% window RTP is impossible on a board whose smallest multiplier is 0.5');
        assert_1.strict.ok(min <= 1.0028 && 1.0028 <= max, 'the committed rtpEarly must stay inside its own board range');
    });
    it('a field with no declared domain is reported rather than waved through', () => {
        const doc = { totalConfigs: 28, somethingNobodyDeclared: 7 };
        const r = (0, domains_1.validateDomains)(doc, rules['coverage-results.json']);
        assert_1.strict.deepEqual(r.uncovered, ['.somethingNobodyDeclared']);
    });
});
describe('value domains: G-VALID — honest values are NOT rejected', () => {
    it('an expected COUNT is a real, not an integer (expectedFlagsByChance = 9.595)', () => {
        assert_1.strict.ok(!domains_1.NONNEG_INT.ok(9.595), 'sanity: 9.595 is not an integer');
        const rules = (0, domains_1.domainRules)(cfg);
        const doc = JSON.parse((0, fs_1.readFileSync)(path.join(OUTPUTS, 'simulation-results.json'), 'utf8'));
        assert_1.strict.equal(doc.pass2_casino_seeds.expectedFlagsByChance, 9.595);
        const r = (0, domains_1.validateDomains)(doc, rules['simulation-results.json']);
        assert_1.strict.ok(!r.violations.some(v => v.path.endsWith('expectedFlagsByChance')));
    });
    it('a window RTP above 1 is attainable and accepted (rtpEarly = 1.0028…)', () => {
        const rules = (0, domains_1.domainRules)(cfg);
        const doc = JSON.parse((0, fs_1.readFileSync)(path.join(OUTPUTS, 'simulation-results.json'), 'utf8'));
        const above = doc.pass2_casino_seeds.results.filter((r) => r.rtpEarly > 1);
        assert_1.strict.ok(above.length > 0, 'expected at least one window RTP above 1 in the committed artifact');
        const r = (0, domains_1.validateDomains)(doc, rules['simulation-results.json']);
        assert_1.strict.ok(!r.violations.some(v => v.path.endsWith('rtpEarly')), 'an RTP above 1 was rejected — a window mean is bounded by the paytable, not by 1');
    });
    it('a percentage is [0,100] and a probability is [0,1]; they are not the same domain', () => {
        assert_1.strict.ok(domains_1.PERCENT.ok(78.1) && !domains_1.PROBABILITY.ok(78.1));
        assert_1.strict.ok(domains_1.PROBABILITY.ok(0.781) && domains_1.PERCENT.ok(0.781));
    });
    it('a correlation may be negative and may sit on its bound', () => {
        assert_1.strict.ok(domains_1.CORRELATION.ok(-0.9999999643182262));
        assert_1.strict.ok(domains_1.CORRELATION.ok(-1) && domains_1.CORRELATION.ok(1) && domains_1.CORRELATION.ok(0));
        assert_1.strict.ok(!domains_1.CORRELATION.ok(-1.0000001));
    });
    it('a z-score is unbounded, so an extreme but genuine run is not rejected', () => {
        assert_1.strict.ok(domains_1.FINITE.ok(-42) && domains_1.FINITE.ok(1e6));
        assert_1.strict.ok(!domains_1.FINITE.ok(NaN) && !domains_1.FINITE.ok(Infinity));
    });
    it('a value landing exactly on its expectation is accepted', () => {
        assert_1.strict.ok(domains_1.PROBABILITY.ok(0.05));
        assert_1.strict.ok(domains_1.NONNEG_INT.ok(0), 'zero failures is an honest result, not an impossible one');
    });
    it('the paytable bounds come from the pinned config, not from any artifact', () => {
        const { min, max } = (0, domains_1.attainableMultiplierRange)(cfg);
        assert_1.strict.equal(min, 0);
        assert_1.strict.equal(max, 1000);
        assert_1.strict.equal((0, domains_1.totalPayoutCells)(cfg), 365);
    });
    it('the committed edge-hit counts are ACCEPTED — the new bound is not too tight', () => {
        const rules = (0, domains_1.domainRules)(cfg);
        const doc = JSON.parse((0, fs_1.readFileSync)(path.join(OUTPUTS, 'simulation-results.json'), 'utf8'));
        const pw = doc.pass2_casino_seeds.payoutWeighted;
        assert_1.strict.ok(pw.edgeHitsEarly > 0 && pw.edgeHitsLate > 0, 'sanity: the committed artifact records edge hits');
        assert_1.strict.ok(pw.edgeHitsEarly <= (0, domains_1.pass2WindowDrops)() && pw.edgeHitsLate <= (0, domains_1.pass2WindowDrops)());
        const r = (0, domains_1.validateDomains)(doc, rules['simulation-results.json']);
        assert_1.strict.ok(!r.violations.some(v => v.path.includes('edgeHits')), 'an honest edge-hit count was rejected by its own bound');
    });
    it('every committed Pass 2 window RTP is inside ITS OWN board\'s range', () => {
        const doc = JSON.parse((0, fs_1.readFileSync)(path.join(OUTPUTS, 'simulation-results.json'), 'utf8'));
        const rows = doc.pass2_casino_seeds.results;
        assert_1.strict.ok(rows.length > 0, 'sanity: the committed artifact has Pass 2 rows');
        for (const r of rows) {
            const { min, max } = (0, domains_1.boardMultiplierRange)(cfg, r.rows, r.riskLevel ?? 3);
            assert_1.strict.ok(r.rtpEarly >= min && r.rtpEarly <= max, `honest rtpEarly ${r.rtpEarly} falls outside [${min}, ${max}] on the ${r.rows}r/risk-${r.riskLevel} board`);
            assert_1.strict.ok(r.rtpLate >= min && r.rtpLate <= max, `honest rtpLate ${r.rtpLate} falls outside [${min}, ${max}] on the ${r.rows}r/risk-${r.riskLevel} board`);
        }
    });
});

},
"tests/plinko/rngTests.js": function(module, exports, require, __filename, __dirname) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const node_assert_1 = require("node:assert");
const rng_1 = require("../../src/rng");
const SERVER_SEED = 'a3f90b1c2d4e5f60718293a4b5c6d7e8';
const CLIENT_SEED = 'client-seed';
describe('rng: HMAC draw validation vectors', () => {
    it('nonce=7 cursor=0 range=25 -> 2', () => {
        node_assert_1.strict.equal((0, rng_1.generateProvablyFairNumber)(SERVER_SEED, CLIENT_SEED, 7, 0, 25), 2);
    });
    it('nonce=7 cursor=3 range=52 -> 49', () => {
        node_assert_1.strict.equal((0, rng_1.generateProvablyFairNumber)(SERVER_SEED, CLIENT_SEED, 7, 3, 52), 49);
    });
});
describe('plinko: real captured bet reproduction', () => {
    it('serverSeed fc9a… clientSeed auditb1141320acde nonce=0 rows=8 -> dropDetails "01101111" slot 6', () => {
        const { path, winningSlot } = (0, rng_1.revealPlinko)('fc9a1d6fad00e0832fddfdea45435c85', 'auditb1141320acde', 0, 8);
        node_assert_1.strict.equal(path, '01101111');
        node_assert_1.strict.equal(winningSlot, 6);
    });
});
describe('rng: commitment hash (SHA-256 of utf8 hex string)', () => {
    it('commitHash reproduces a known hashedServerSeed', () => {
        node_assert_1.strict.equal((0, rng_1.commitHash)('fc9a1d6fad00e0832fddfdea45435c85'), '3b34a0fce5732f2d9c89b16fca9c2b6a231c2b7f2de29bbc41e141861dc39d36');
    });
});

},
"tests/plinko/rtpPinTests.js": function(module, exports, require, __filename, __dirname) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const node_assert_1 = require("node:assert");
const config_1 = require("../../src/config");
const TOL = 1e-12;
describe('plinko: published RTP figures pinned at full precision', () => {
    const cfg = (0, config_1.loadPlinkoConfig)();
    const rtps = (0, config_1.allConfigs)(cfg).map(c => (0, config_1.theoreticalRTP)(cfg, c.rows, c.riskLevel));
    it('min per-config RTP = 0.9890625 (98.90625%)', () => {
        node_assert_1.strict.ok(Math.abs(Math.min(...rtps) - 0.9890625) < TOL);
    });
    it('max per-config RTP = 0.9916015625 (99.16016%)', () => {
        node_assert_1.strict.ok(Math.abs(Math.max(...rtps) - 0.9916015625) < TOL);
    });
    it('equal-weighted mean over 28 configs = 0.990152413504464 (99.0152%)', () => {
        node_assert_1.strict.equal(rtps.length, 28, 'config count changed — the published mean is over 28');
        const mean = rtps.reduce((a, b) => a + b, 0) / rtps.length;
        node_assert_1.strict.ok(Math.abs(mean - 0.990152413504464) < TOL);
    });
    it('WTF RTP = 0.989990234375 (98.9990%)', () => {
        const wtf = (0, config_1.theoreticalRTP)(cfg, cfg.wtf_mode.rows, cfg.wtf_mode.riskLevel);
        node_assert_1.strict.ok(Math.abs(wtf - 0.989990234375) < TOL);
    });
    it('WTF zero-payout probability = 0.99658203125 (99.6582%)', () => {
        let pPay = 0;
        for (let k = 0; k <= cfg.wtf_mode.rows; k++) {
            if (cfg.wtf_mode.odds[k] > 0)
                pPay += (0, config_1.binomP)(cfg.wtf_mode.rows, k);
        }
        node_assert_1.strict.ok(Math.abs((1 - pPay) - 0.99658203125) < TOL);
    });
});

}
};
// Bundled modules receive their original directory paths for evidence-file lookup.
const __path = require('node:path');
const __createRequire = require('node:module').createRequire;
const __cache = new Map();
function __load(id) {
  if (__cache.has(id)) return __cache.get(id).exports;
  if (!Object.hasOwn(__modules, id)) throw new Error(`Missing bundled module: ${id}`);
  const filename = __path.join(__dirname, id);
  const diskRequire = __createRequire(filename);
  const module = { exports: {} };
  __cache.set(id, module);
  const localRequire = spec => {
    if (!spec.startsWith('.')) return diskRequire(spec);
    const joined = __path.posix.normalize(__path.posix.join(__path.posix.dirname(id), spec));
    const target = [joined, joined + '.js', joined + '/index.js']
      .find(candidate => Object.hasOwn(__modules, candidate));
    return target ? __load(target) : diskRequire(spec);
  };
  __modules[id](module, module.exports, localRequire, filename, __path.dirname(filename));
  return module.exports;
}

// The unit sources use Mocha's describe/it interface and synchronous timeout settings.
// Node's built-in runner supplies assertion reporting and a nonzero failure exit status.
function __installTestGlobals() {
  const test = require('node:test');
  const context = () => ({ timeout() {}, slow() {}, retries() {} });
  const wrap = fn => typeof fn === 'function' ? function () { return fn.call(context()); } : fn;
  for (const name of ['describe', 'it']) {
    const bind = fn => (title, callback) => fn(title, wrap(callback));
    const bound = bind(test[name]);
    for (const modifier of ['skip', 'only', 'todo']) bound[modifier] = bind(test[name][modifier]);
    globalThis[name] = bound;
  }
  for (const name of ['before', 'after', 'beforeEach', 'afterEach']) {
    globalThis[name] = callback => test[name](wrap(callback));
  }
}

__installTestGlobals();
__load("tests/plinko/calibrationTests.js");
__load("tests/plinko/domainTests.js");
__load("tests/plinko/rngTests.js");
__load("tests/plinko/rtpPinTests.js");
